config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.super_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  # shrine direct uploader https://github.com/shrinerb/shrine/wiki/Adding-Direct-S3-Uploads
  mount ImageCacheUploader.upload_endpoint(:store) => '/image_cache_uploader/upload'

  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'
  root 'pages#index'

  # Webhook URL
  resources :webhooks, except: :all do
    collection do
      post 'sms-receipt', to: 'webhooks#sms_receipt'
    end
  end

  resources :search, only: [:index] do
    collection do
      get 'view_results/:group/:keyword', as: :view_results, to: 'search#view_results'
    end
  end
  resources :notifications, only: [:index]
  resources :organisations, only: [:show]
  resources :posts do
    collection do
      get :my_posts
      get :favorites
    end

    member do
      put :toggle_favorite
      put :toggle_like
    end
  end
  resources :regions, path: 'region', only: [:show]
  resources :rohes, path: 'rohe', only: [:show]
  resources :iwis, path: 'iwi', only: [:show] do
    member do
      get :get_hapu
    end
  end
  resources :hapus, path: 'hapu', only: [:show]
  resources :maraes, path: 'marae', only: [:show]
  resources :wharenuis, path: 'wharenui', only: [:show]
  resources :maps, only: [:index]
  
  devise_for :users, controllers: {
    two_factor_authentication: 'users/two_factor_authentication',
    sessions: 'users/sessions'
  }, skip: %[registrations]
  devise_scope :user do
    resource :registration,
      only: %w[new create],
      path: 'users',
      controller: 'users/registrations'
  end

  namespace :users do
    resources :setup_account
    resources :user_invitation_friendships, path: 'friend-invitations', only: [:index] do
      collection do
        post '/:user_friend_id', to: 'user_invitation_friendships#create', as: :create
        delete '/:user_friend_id', to: 'user_invitation_friendships#destroy', as: :destroy
        delete ':user_friend_id/unfriend', to: 'user_invitation_friendships#unfriend', as: :unfriend
        put ':user_friend_id/:status', to: 'user_invitation_friendships#update', as: :update
      end
    end
    resources :profile, only: [:index] do
      collection do
        get :edit
        patch :update
        patch :update_location
      end
    end
  end

  namespace :admin do
    resources :health_providers, except: [:show]
    resources :appointments
    resources :organisations, except: [:show] do
      resources :locations, except: [:show]
    end
    resources :pages, only: [:index, :edit, :update]
    resources :users, except: [:show]
    resources :regions, path: 'region', except: [:show]
    resources :rohes, path: 'rohe', except: [:show]
    resources :wharenuis, path: 'wharenui', except: [:show]
    resources :iwis, path: 'iwi', except: [:show] do
      member do
        get ':id/show' => 'iwis#show'
      end
    end
    resources :hapus, path: 'hapu', except: [:show] do
      member do
        get ':id/show' => 'hapus#show'
      end
    end

    resources :maraes, path: 'marae', except: [:show] do
      member do
        get ':id/show' => 'marae#show'
      end
    end
  end

  namespace :health_admin, path: 'health-admin' do
    resources :health_providers, except: [:show]
    resources :appointments
  end

  namespace :corona, path: 'covid-19' do
    root :to => 'pages#index'

    get 'health-provider-maps' => 'health_providers#index'
    get 'health-provider-list' => 'health_providers#index_list'

    resources :posts, only: [:index, :show]

    get 'medical-checkup', to: 'pages#medical_checkup'
    resources :health_providers, path: 'health-providers', only: [:show] do
      get 'appointment', to: 'appointments#new'
      post 'appointment', to: 'appointments#create'
      get 'appointment-success', to: 'appointments#success'
    end

    resources :appointments, only: [:show, :index]

    get 'health-status', to: 'pages#health_status'

    # invitation signup
    get 'health-status/invitation-signup', to: 'user_invitation_signup#index'
    post 'health-status/invitation-signup', to: 'user_invitation_signup#create'
  end

  resources :users, only: [:show]

  get ':page', as: :page_show, to: 'pages#show'
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  include LocationGeocoder

  acts_as_geolocated

  validates :address, presence: true

  belongs_to :locationable, polymorphic: true, touch: true

  scope :latitude_longitude_present, -> { where.not(latitude: nil).where.not(longitude: nil) }
end

# == Schema Information
#
# Table name: locations
#
#  id                :bigint           not null, primary key
#  address           :text             not null
#  contact           :text
#  country           :string
#  latitude          :float
#  locationable_type :string
#  longitude         :float
#  postcode          :string
#  suburb            :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  locationable_id   :bigint
#
# Indexes
#
#  index_locations_on_locationable_type_and_locationable_id  (locationable_type,locationable_id)
#

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::ApplicationController
  before_action :set_organisation
  before_action :set_location, only: %w[edit update destroy]

  def index
    @locations = @organisation.locations
  end

  def new
    @location = @organisation.locations.new
  end

  def edit; end

  def create
    @location = @organisation.locations.new(location_params)

    if @location.save
      redirect_to admin_organisation_locations_path(@organisation), notice: 'Location was successfully created.'
    else
      @back_link = admin_organisation_locations_path(@organisation)
      render :new
    end
  end

  def update
    if @location.update(location_params)
      redirect_to admin_organisation_locations_path(@organisation), notice: 'Location was successfully updated.'
    else
      @back_link = admin_organisation_locations_path(@organisation)
      render :edit
    end
  end

  def destroy
    if @location.destroy
      redirect_to admin_organisation_locations_path(@organisation), notice: 'Location was successfully destroyed.'
    end
  end

  private
  def set_location
    @location = @organisation.locations.find(params[:id])
  end
  
  def set_organisation
    @organisation = Organisation.friendly.find(params[:organisation_id])
  end

  def location_params
    params.require(:location).permit(:address, :suburb, :country,
      :postcode, :latitude, :longitude, :contact)
    .merge(turn_off_geocoder: true)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_organisation
  before_action :set_location, only: %w[edit update destroy]

  def index
    @locations = @organisation.locations
  end

  def new
    @location = @organisation.locations.new
  end

  def edit; end

  def create
    @location = @organisation.locations.new(location_params)

    if @location.save
      redirect_to organisation_locations_path(@organisation), notice: 'Location was successfully created.'
    else
      @back_link = organisation_locations_path(@organisation)
      render :new
    end
  end

  def update
    if @location.update(location_params)
      redirect_to organisation_locations_path(@organisation), notice: 'Location was successfully updated.'
    else
      @back_link = organisation_locations_path(@organisation)
      render :edit
    end
  end

  def destroy
    if @location.destroy
      redirect_to organisation_locations_path(@organisation), notice: 'Location was successfully destroyed.'
    end
  end

  private
  def set_location
    @location = @organisation.locations.find(params[:id])
  end
  
  def set_organisation
    @organisation = Organisation.friendly.find(params[:organisation_id])
    authorize @organisation, :access_location?
  end

  def location_params
    params.require(:location).permit(:address, :suburb, :country,
      :postcode, :latitude, :longitude, :contact)
    .merge(turn_off_geocoder: true)
  end
end

app/views/admin/locations/_form.html.erb
<%= simple_form_for([:admin, organisation, location]) do |f| %>
  <%= bootstrap_error(location) %>
  <%= text_field_tag 'pac-input', nil, id: 'pac-input', class: 'controls', placeholder: 'Enter your addresshere', value: f.object.address %>
  <div id="map" class="map-style" data-target='location' data-google-map-id="<%= ENV['GOOGLE_MAP_API_KEY'] %>"></div>
  <div class="hide">
    <%= f.hidden_field :latitude, readonly: true %>
    <%= f.hidden_field :longitude, readonly: true %>
    <%= f.hidden_field :country, readonly: true %>
  </div>
  <%= f.input :address %>
  <%= f.input :suburb %>
  <%= f.input :postcode %>
  <%= f.input :contact %>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/admin/locations/edit.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>Edit Location</h1>
    </div>
    <div class="search-content pb-4">
      <%= render partial: 'form', locals: { organisation: @organisation, location: @location } %>
    </div>
  </div>
</section>

app/views/admin/locations/index.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>Location of <%= @organisation.name %></h1>
    </div>
    <div class="row mb-3">
      <div class="col-md-12 text-right">
        <% if current_user.present? %>
          <%= link_to 'new location', new_admin_organisation_location_path(@organisation), class: 'btn btn-primary btn-md' %>
        <% end %>
      </div>
    </div>
    <div class="search-content pb-4">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th class="width-table-name">Address</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @locations.each do |location| %>
              <tr>
                <td>
                  <%= location.address %>
                </td>
                <td class="text-right">
                  <%= link_to edit_admin_organisation_location_path(@organisation, location), class: 'btn btn-primary btn-sm' do %>
                    <i class="far fa-edit"></i> <span class="d-none d-sm-inline">Edit</span>
                  <% end %>
                  <%= link_to admin_organisation_location_path(@organisation, location), data: { confirm: "Are you sure to delete location" }, method: :delete, class: 'btn btn-danger btn-sm' do %>
                    <i class="fas fa-trash"></i> <span class="d-none d-sm-inline">Delete</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/admin/locations/new.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>New Location</h1>
    </div>
    <div class="search-content pb-4">
      <%= render partial: 'form', locals: { organisation: @organisation, location: @location } %>
    </div>
  </div>
</section>