config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.super_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  # shrine direct uploader https://github.com/shrinerb/shrine/wiki/Adding-Direct-S3-Uploads
  mount ImageCacheUploader.upload_endpoint(:store) => '/image_cache_uploader/upload'

  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'
  root 'pages#index'

  # Webhook URL
  resources :webhooks, except: :all do
    collection do
      post 'sms-receipt', to: 'webhooks#sms_receipt'
    end
  end

  resources :search, only: [:index] do
    collection do
      get 'view_results/:group/:keyword', as: :view_results, to: 'search#view_results'
    end
  end
  resources :notifications, only: [:index]
  resources :organisations, only: [:show]
  resources :posts do
    collection do
      get :my_posts
      get :favorites
    end

    member do
      put :toggle_favorite
      put :toggle_like
    end
  end
  resources :regions, path: 'region', only: [:show]
  resources :rohes, path: 'rohe', only: [:show]
  resources :iwis, path: 'iwi', only: [:show] do
    member do
      get :get_hapu
    end
  end
  resources :hapus, path: 'hapu', only: [:show]
  resources :maraes, path: 'marae', only: [:show]
  resources :wharenuis, path: 'wharenui', only: [:show]
  resources :maps, only: [:index]
  
  devise_for :users, controllers: {
    two_factor_authentication: 'users/two_factor_authentication',
    sessions: 'users/sessions'
  }, skip: %[registrations]
  devise_scope :user do
    resource :registration,
      only: %w[new create],
      path: 'users',
      controller: 'users/registrations'
  end

  namespace :users do
    resources :setup_account
    resources :user_invitation_friendships, path: 'friend-invitations', only: [:index] do
      collection do
        post '/:user_friend_id', to: 'user_invitation_friendships#create', as: :create
        delete '/:user_friend_id', to: 'user_invitation_friendships#destroy', as: :destroy
        delete ':user_friend_id/unfriend', to: 'user_invitation_friendships#unfriend', as: :unfriend
        put ':user_friend_id/:status', to: 'user_invitation_friendships#update', as: :update
      end
    end
    resources :profile, only: [:index] do
      collection do
        get :edit
        patch :update
        patch :update_location
      end
    end
  end

  namespace :admin do
    resources :health_providers, except: [:show]
    resources :appointments
    resources :organisations, except: [:show] do
      resources :locations, except: [:show]
    end
    resources :pages, only: [:index, :edit, :update]
    resources :users, except: [:show]
    resources :regions, path: 'region', except: [:show]
    resources :rohes, path: 'rohe', except: [:show]
    resources :wharenuis, path: 'wharenui', except: [:show]
    resources :iwis, path: 'iwi', except: [:show] do
      member do
        get ':id/show' => 'iwis#show'
      end
    end
    resources :hapus, path: 'hapu', except: [:show] do
      member do
        get ':id/show' => 'hapus#show'
      end
    end

    resources :maraes, path: 'marae', except: [:show] do
      member do
        get ':id/show' => 'marae#show'
      end
    end
  end

  namespace :health_admin, path: 'health-admin' do
    resources :health_providers, except: [:show]
    resources :appointments
  end

  namespace :corona, path: 'covid-19' do
    root :to => 'pages#index'

    get 'health-provider-maps' => 'health_providers#index'
    get 'health-provider-list' => 'health_providers#index_list'

    resources :posts, only: [:index, :show]

    get 'medical-checkup', to: 'pages#medical_checkup'
    resources :health_providers, path: 'health-providers', only: [:show] do
      get 'appointment', to: 'appointments#new'
      post 'appointment', to: 'appointments#create'
      get 'appointment-success', to: 'appointments#success'
    end

    resources :appointments, only: [:show, :index]

    get 'health-status', to: 'pages#health_status'

    # invitation signup
    get 'health-status/invitation-signup', to: 'user_invitation_signup#index'
    post 'health-status/invitation-signup', to: 'user_invitation_signup#create'
  end

  resources :users, only: [:show]

  get ':page', as: :page_show, to: 'pages#show'
end

app/models/iwi.rb
# frozen_string_literal: true

class Iwi < ApplicationRecord
  include InfoData

  has_and_belongs_to_many :rohes, :join_table => :rohes_iwis
  has_and_belongs_to_many :hapus, :join_table => :iwis_hapus
  has_and_belongs_to_many :maraes, :join_table => :iwis_maraes
  has_and_belongs_to_many :wharenuis, :join_table => :iwis_wharenuis
  has_and_belongs_to_many :organisations, :join_table => :iwis_organisations
  has_many :regions, through: :rohes

  validates :name, presence: true
end

# == Schema Information
#
# Table name: iwis
#
#  id       :bigint           not null, primary key
#  abstract :text
#  contact  :text
#  name     :string           not null
#  slug     :string           not null
#

app/controllers/admin/iwis_controller.rb
class Admin::IwisController < Admin::ApplicationController
  before_action :set_iwi, only: [:show, :edit, :update, :destroy]
  def index
    @iwis = Iwi.search_filters(params: filter_params).page(params[:page])
  end

  def new
    @iwi = Iwi.new
  end

  def show; end

  def create
    @iwi = Iwi.new(iwi_params)

    if @iwi.save
      redirect_to admin_iwis_path, flash: { success: 'Successful create iwi' }
    else
      render :new
    end
  end

  def edit; end

  def update
    if @iwi.update(iwi_params)
      redirect_to admin_iwis_path, flash: { success: 'Successful create iwi' }
    else
      render :edit
    end
  end

  def destroy
    if @iwi.destroy
      redirect_to admin_iwis_path, flash: { success: 'Successful delete iwi' }
    else
      redirect_to admin_iwis_path, flash: { error: 'Cannot delete iwi' }
    end
  end

  private

  def set_iwi
    @iwi = Iwi.friendly.find(params[:id])
  end
  
  def iwi_params
    params.require(:iwi).permit(:name, :contact, :abstract, rohe_ids: [], hapu_ids: [])
  end
end

app/controllers/iwis_controller.rb
class IwisController < ApplicationController
  before_action :set_iwi, except: [:get_hapu]

  def show; end

  def get_hapu
    iwi = Iwi.find(params[:id])
    respond_to do |format|
      format.json { render json: iwi.hapus.pluck(:name, :id).to_json }
    end
  end

  private

  def set_iwi
    @iwi = Iwi.friendly.find(params[:id])
  end
end

app/views/admin/iwis/_form.html.erb
<%= simple_form_for iwi, url: url do |f| %>
  <%= f.input :name, required: true %>
  <%= f.input :contact %>
  <%= f.input :abstract %>
  <div class="row">
    <div class="col-lg-12">
      <%= f.input :rohe_ids, as: :select, collection: Rohe.all.pluck(:name, :id), label: 'Rohe', input_html: { placeholder: 'Rohe', multiple: true, class: 'select2-tagging' }, required: false %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <%= f.input :hapu_ids, as: :select, collection: Hapu.all.pluck(:name, :id), label: 'Hapu', input_html: { placeholder: 'Hapu', multiple: true, class: 'select2-tagging' }, required: false %>
    </div>
  </div>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/admin/iwis/edit.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>Edit Iwi</h1>
    </div>
    <div class="search-content pb-4">
      <%= render partial: 'form', locals: { iwi: @iwi, url: admin_iwi_path(@iwi) } %>
    </div>
  </div>
</section>

app/views/admin/iwis/index.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>Iwi</h1>
    </div>
    <div class="row">
      <div class="col-md-8">
        <%= simple_form_for :search, method: :get do |f| %>
          <div class="input-group mb-3">
            <%= f.input :keyword, required: false, label: false, wrapper: false, placeholder: 'search by keyword', input_html: { name: 'keyword', value: params[:keyword] } %>
            <div class="input-group-prepend">
              <%= f.submit :search, class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-4 text-right">
        <%= link_to 'new iwi', new_admin_iwi_path, class: 'btn btn-primary btn-md' %>
      </div>
    </div>
    <div class="search-content pb-4">
      <% if @iwis.present? %>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th class="width-table-name">Name</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @iwis.each do |iwi| %>
                <tr>
                  <td scope="row"><%= iwi.name %></td>
                  <td class="text-right">
                    <%= link_to iwi_path(iwi), class: 'btn btn-success btn-sm' do %>
                      <i class="far fa-eye"></i> <span class="d-none d-sm-inline">Show</span>
                    <% end %>
                    <%= link_to edit_admin_iwi_path(iwi), class: 'btn btn-primary btn-sm' do %>
                      <i class="far fa-edit"></i> <span class="d-none d-sm-inline">Edit</span>
                    <% end %>
                    <%= link_to admin_iwi_path(iwi), data: { confirm: "Are you sure to delete #{iwi.name}" }, method: :delete, class: 'btn btn-danger btn-sm' do %>
                      <i class="fas fa-trash"></i> <span class="d-none d-sm-inline">Delete</span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <hr/>
        <div class="row">
          <div class="col text-right">
            <span style="display: inline-block">
              <%= paginate @iwis, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", window: 1 %>
            </span>
          </div>
        </div>
      <% else %>
        <h4 class="text-center mt-5">No Result Found</h4>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/iwis/new.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>New Iwi</h1>
    </div>
    <div class="search-content pb-4">
      <%= render partial: 'form', locals: { iwi: @iwi, url: admin_iwis_path } %>
    </div>
  </div>
</section>