config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.super_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  # shrine direct uploader https://github.com/shrinerb/shrine/wiki/Adding-Direct-S3-Uploads
  mount ImageCacheUploader.upload_endpoint(:store) => '/image_cache_uploader/upload'

  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'
  root 'pages#index'

  # Webhook URL
  resources :webhooks, except: :all do
    collection do
      post 'sms-receipt', to: 'webhooks#sms_receipt'
    end
  end

  resources :search, only: [:index] do
    collection do
      get 'view_results/:group/:keyword', as: :view_results, to: 'search#view_results'
    end
  end
  resources :notifications, only: [:index]
  resources :organisations, only: [:show]
  resources :posts do
    collection do
      get :my_posts
      get :favorites
    end

    member do
      put :toggle_favorite
      put :toggle_like
    end
  end
  resources :regions, path: 'region', only: [:show]
  resources :rohes, path: 'rohe', only: [:show]
  resources :iwis, path: 'iwi', only: [:show] do
    member do
      get :get_hapu
    end
  end
  resources :hapus, path: 'hapu', only: [:show]
  resources :maraes, path: 'marae', only: [:show]
  resources :wharenuis, path: 'wharenui', only: [:show]
  resources :maps, only: [:index]
  
  devise_for :users, controllers: {
    two_factor_authentication: 'users/two_factor_authentication',
    sessions: 'users/sessions'
  }, skip: %[registrations]
  devise_scope :user do
    resource :registration,
      only: %w[new create],
      path: 'users',
      controller: 'users/registrations'
  end

  namespace :users do
    resources :setup_account
    resources :user_invitation_friendships, path: 'friend-invitations', only: [:index] do
      collection do
        post '/:user_friend_id', to: 'user_invitation_friendships#create', as: :create
        delete '/:user_friend_id', to: 'user_invitation_friendships#destroy', as: :destroy
        delete ':user_friend_id/unfriend', to: 'user_invitation_friendships#unfriend', as: :unfriend
        put ':user_friend_id/:status', to: 'user_invitation_friendships#update', as: :update
      end
    end
    resources :profile, only: [:index] do
      collection do
        get :edit
        patch :update
        patch :update_location
      end
    end
  end

  namespace :admin do
    resources :health_providers, except: [:show]
    resources :appointments
    resources :organisations, except: [:show] do
      resources :locations, except: [:show]
    end
    resources :pages, only: [:index, :edit, :update]
    resources :users, except: [:show]
    resources :regions, path: 'region', except: [:show]
    resources :rohes, path: 'rohe', except: [:show]
    resources :wharenuis, path: 'wharenui', except: [:show]
    resources :iwis, path: 'iwi', except: [:show] do
      member do
        get ':id/show' => 'iwis#show'
      end
    end
    resources :hapus, path: 'hapu', except: [:show] do
      member do
        get ':id/show' => 'hapus#show'
      end
    end

    resources :maraes, path: 'marae', except: [:show] do
      member do
        get ':id/show' => 'marae#show'
      end
    end
  end

  namespace :health_admin, path: 'health-admin' do
    resources :health_providers, except: [:show]
    resources :appointments
  end

  namespace :corona, path: 'covid-19' do
    root :to => 'pages#index'

    get 'health-provider-maps' => 'health_providers#index'
    get 'health-provider-list' => 'health_providers#index_list'

    resources :posts, only: [:index, :show]

    get 'medical-checkup', to: 'pages#medical_checkup'
    resources :health_providers, path: 'health-providers', only: [:show] do
      get 'appointment', to: 'appointments#new'
      post 'appointment', to: 'appointments#create'
      get 'appointment-success', to: 'appointments#success'
    end

    resources :appointments, only: [:show, :index]

    get 'health-status', to: 'pages#health_status'

    # invitation signup
    get 'health-status/invitation-signup', to: 'user_invitation_signup#index'
    post 'health-status/invitation-signup', to: 'user_invitation_signup#create'
  end

  resources :users, only: [:show]

  get ':page', as: :page_show, to: 'pages#show'
end

app/models/marae.rb
# frozen_string_literal: true

class Marae < ApplicationRecord
  include InfoMap
  include InfoData
  include LocationGeocoder

  has_and_belongs_to_many :hapus, :join_table => :hapus_maraes
  has_and_belongs_to_many :iwis, :join_table => :iwis_maraes
  has_and_belongs_to_many :rohes, :join_table => :rohes_maraes
  has_and_belongs_to_many :wharenuis, :join_table => :maraes_wharenuis
  has_many :regions, through: :rohes

  multisearchable against: [:name, :contact, :suburb, :postcode]

  validates :name, presence: true
end

# == Schema Information
#
# Table name: maraes
#
#  id        :bigint           not null, primary key
#  abstract  :text
#  address   :text
#  contact   :text
#  country   :string
#  latitude  :float
#  longitude :float
#  name      :string           not null
#  postcode  :string
#  slug      :string           not null
#  suburb    :string
#

app/controllers/admin/maraes_controller.rb
class Admin::MaraesController < Admin::ApplicationController
  before_action :set_marae, only: [:show, :edit, :update, :destroy]

  def index
    @maraes = Marae.search_filters(params: filter_params).page(params[:page])
  end

  def new
    @marae = Marae.new
  end

  def edit; end

  def create
    @marae = Marae.new(marae_params)

    if @marae.save
      redirect_to admin_maraes_path, notice: 'Marae was successfully created.'
    else
      render :new
    end
  end

  def update
    if @marae.update(marae_params)
      redirect_to admin_maraes_path, notice: 'Marae was successfully update.'
    else
      render :edit
    end
  end

  def destroy
    if @marae.destroy
      redirect_to admin_maraes_path, flash: { success: 'Successful delete marae' }
    else
      redirect_to admin_maraes_path, flash: { error: 'Cannot delete marae' }
    end
  end

  private
  
  def set_marae
    @marae = Marae.friendly.find(params[:id])
  end

  def marae_params
    params.require(:marae).permit(:name, :address, :suburb, :country,
      :postcode, :latitude, :longitude, :contact, :abstract, 
      iwi_ids: [], hapu_ids: [], wharenui_ids: [])
    .merge(turn_off_geocoder: true)
  end
end

app/controllers/maraes_controller.rb
class MaraesController < ApplicationController
  before_action :set_marae

  def show; end

  private

  def set_marae
    @marae = Marae.friendly.find(params[:id])
  end
end

app/views/admin/maraes/_form.html.erb
<%= simple_form_for marae, url: url do |f| %>
  <%= bootstrap_error(marae) %>

  <%= f.input :name, required: true %>
  <%= text_field_tag 'pac-input', nil, id: 'pac-input', class: 'controls', placeholder: 'Enter your addresshere', value: f.object.address %>
  <div id="map" class="map-style" data-target='marae' data-google-map-id="<%= ENV['GOOGLE_MAP_API_KEY'] %>"></div>
  <div class="hide">
    <%= f.hidden_field :latitude, readonly: true %>
    <%= f.hidden_field :longitude, readonly: true %>
    <%= f.hidden_field :country, readonly: true %>
  </div>
  <%= f.input :address %>
  <%= f.input :suburb %>
  <%= f.input :postcode %>
  <%= f.input :contact %>
  <%= f.input :abstract %>
  <%= f.input :iwi_ids, as: :select, collection: Iwi.all.pluck(:name, :id), label: 'Iwi', input_html: { placeholder: 'Iwi', multiple: true, class: 'select2-tagging' }, required: false %>
  <%= f.input :hapu_ids, as: :select, collection: Hapu.all.pluck(:name, :id), label: 'Hapu', input_html: { placeholder: 'Hapu', multiple: true, class: 'select2-tagging' }, required: false %>
  <%= f.input :wharenui_ids, as: :select, collection: Wharenui.all.pluck(:name, :id), label: 'Wharenui', input_html: { placeholder: 'Wharenui', multiple: true, class: 'select2-tagging' }, required: false %>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/admin/maraes/edit.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>Edit Marae</h1>
    </div>
    <div class="search-content pb-4">
      <%= render partial: 'form', locals: { marae: @marae, url: admin_marae_path(@marae) } %>
    </div>
  </div>
</section>

app/views/admin/maraes/index.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>Marae</h1>
    </div>
    <div class="row">
      <div class="col-md-8">
        <%= simple_form_for :search, method: :get do |f| %>
          <div class="input-group mb-3">
            <%= f.input :keyword, required: false, label: false, wrapper: false, placeholder: 'search by keyword', input_html: { name: 'keyword', value: params[:keyword] } %>
            <div class="input-group-prepend">
              <%= f.submit :search, class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-4 text-right">
        <%= link_to 'new marae', new_admin_marae_path, class: 'btn btn-primary btn-md' %>
      </div>
    </div>
    <div class="search-content pb-4">
      <% if @maraes.present? %>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th class="width-table-name">Name</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @maraes.each do |marae| %>
                <tr>
                  <td scope="row"><%= marae.name %></td>
                  <td class="text-right">
                    <%= link_to marae_path(marae), class: 'btn btn-success btn-sm' do %>
                      <i class="far fa-eye"></i> <span class="d-none d-sm-inline">Show</span>
                    <% end %>
                    <%= link_to edit_admin_marae_path(marae), class: 'btn btn-primary btn-sm' do %>
                      <i class="far fa-edit"></i> <span class="d-none d-sm-inline">Edit</span>
                    <% end %>
                    <%= link_to admin_marae_path(marae), data: { confirm: "Are you sure to delete #{marae.name}" }, method: :delete, class: 'btn btn-danger btn-sm' do %>
                      <i class="fas fa-trash"></i> <span class="d-none d-sm-inline">Delete</span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <hr/>
        <div class="row">
          <div class="col text-right">
            <span style="display: inline-block">
              <%= paginate @maraes, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm", window: 1 %>
            </span>
          </div>
        </div>
      <% else %>
        <h4 class="text-center mt-5">No Result Found</h4>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/maraes/new.html.erb
<!-- Begin page Content -->
<section class="search-result">
  <div class="container px-4">
    <div class="search-title mb-3 pt-3">
      <h1>New Marae</h1>
    </div>
    <div class="search-content pb-4">
      <%= render partial: 'form', locals: { marae: @marae, url: admin_maraes_path } %>
    </div>
  </div>
</section>